---
build_from:
  aarch64: "ghcr.io/hassio-addons/base:17.2.5"
  amd64: "ghcr.io/hassio-addons/base:17.2.5"
  armv7: "ghcr.io/hassio-addons/base:17.2.5"
codenotary:
  base_image: therickys93@gmail.com
  signer: therickys93@gmail.com
