---
name: therickys93's Uptime Kuma
version: dev
slug: therickys93-uptime-kuma
description: It is a self-hosted monitoring tool like "Uptime Robot"
url: https://github.com/therickys93/addon-uptimekuma
codenotary: therickys93@gmail.com
webui: http://[HOST]:[PORT:3002]
init: false
arch:
  - aarch64
  - amd64
  - armv7
ports:
  3001/tcp: 3002
ports_description:
  3001/tcp: Web interface
image: "ghcr.io/therickys93/{arch}-addon-uptimekuma"
