---
name: therickys93's Uptime Kuma
version: 0.0.9
slug: therickys93-uptime-kuma
description: therickys93's Uptime Kuma version with notifications on Maintenance Mode.
url: https://github.com/therickys93/addon-uptimekuma
codenotary: therickys93@gmail.com
webui: http://[HOST]:[PORT:3002]
init: false
arch:
  - aarch64
  - amd64
  - armv7
ports:
  3001/tcp: 3002
ports_description:
  3001/tcp: Web interface
image: "ghcr.io/therickys93/{arch}-addon-uptimekuma"
